apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildteam-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "19ffb1d6-c0c0-48a8-85c0-0a5586e6055b"
  labels:
    azure.workload.identity/use: "true"
