apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: buildteam-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "19ffb1d6-c0c0-48a8-85c0-0a5586e6055b"
    keyvaultName: "kv-autodev-qqq"
    tenantId: "86289156-afdb-4440-9b1a-3d8764de69e1"
    objects: |
      array:
        - |
          objectName: githubpat
          objectType: secret
  secretObjects:
    - secretName: buildteam-secrets
      type: Opaque
      data:
        - objectName: githubpat
          key: github-token
